name: npm-publish

on:
  push:
    branches:
      - 'master'


jobs:
  dev-npm-publish:
    name: dev-npm-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Resolve version
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: "Version based on commit: 0.0.0-dev.${{ steps.vars.outputs.sha_short }}"
        run: npm version 0.0.0-dev.${{ steps.vars.outputs.sha_short }} --force --no-git-tag-version
      - name: Build
        run: yarn --frozen-lockfile && yarn run build && yarn run test
        env:
          MAINNET_ETHERSCAN_API_KEY: ${{ secrets.MAINNET_ETHERSCAN_API_KEY }}
          POLYGON_ETHERSCAN_API_KEY: ${{ secrets.POLYGON_ETHERSCAN_API_KEY }}
      - name: Publish Dev Release
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          tag: dev
          access: public

