name: npm-publish

on:
  release:
    types: [released]

jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Build
        run: yarn --frozen-lockfile && yarn run build
      - name: Publish Production Release
        if: |
          !(contains(github.ref, 'beta') || contains(github.ref, 'dev'))
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          tag: latest
      - name: Publish Beta Release
        if: "contains(github.ref, 'beta')"
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          tag: beta
